{{- if .Values.controller.enabled -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "dask-gateway.controllerName" . }}
  labels:
    {{- include "dask-gateway.labels" . | nindent 4 }}
data:
  dask_gateway_config.py: |-
    # Configure addresses
    c.KubeController.address = ":8000"
    c.KubeController.api_url = 'http://{{ include "dask-gateway.apiName" . }}.{{ .Release.Namespace }}:8000/api'
    c.KubeController.gateway_instance = '{{ include "dask-gateway.fullname" . }}'
    c.KubeController.proxy_prefix = "{{ .Values.gateway.prefix }}"
    c.KubeController.proxy_web_middlewares = [
      {"name": '{{ include "dask-gateway.fullname" . | printf "clusters-prefix-%s" | trunc 63 | trimSuffix "-" }}'}
    ]
    c.KubeController.log_level = "{{ .Values.controller.loglevel }}"
    c.KubeController.completed_cluster_max_age = {{ .Values.controller.completedClusterMaxAge }}
    c.KubeController.completed_cluster_cleanup_period = {{ .Values.controller.completedClusterCleanupPeriod }}
{{- end }}
