{{- if .Values.controller.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "dask-gateway.fullname" . | printf "clusters-prefix-%s" | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "dask-gateway.labels" . | nindent 4 }}
spec:
  stripPrefixRegex:
    regex:
      - "{{ .Values.gateway.prefix }}clusters/[a-zA-Z0-9.-]+/"
{{- end }}
