{{- if .Values.controller.enabled -}}
{{- if .Values.rbac.enabled -}}
{{- if not .Values.rbac.controller.serviceAccountName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dask-gateway.controllerName" . }}
  labels:
    {{- include "dask-gateway.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "dask-gateway.controllerName" . }}
  labels:
    {{- include "dask-gateway.labels" . | nindent 4 }}
rules:
  - apiGroups: ["gateway.dask.org"]
    resources: ["daskclusters", "daskclusters/status"]
    verbs: ["*"]
  - apiGroups: ["traefik.containo.us"]
    resources: ["ingressroutes", "ingressroutetcps"]
    verbs: ["get", "create", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets", "services"]
    verbs: ["create", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "dask-gateway.controllerName" . }}
  labels:
    {{- include "dask-gateway.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "dask-gateway.controllerName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "dask-gateway.controllerName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
{{- end }}
