gateway:
  image:
    tag: dev

  backend:
    image:
      tag: dev

    scheduler:
      cores:
        request: 0.1
      memory:
        request: 256M

    worker:
      cores:
        request: 0.1
      memory:
        request: 256M

traefik:
  service:
    type: NodePort
    ports:
      web:
        nodePort: 30200
      tcp:
        nodePort: 30201
