gateway:
  loglevel: DEBUG
  backend:
    scheduler:
      cores:
        request: 0.1
      memory:
        request: 256M

    worker:
      cores:
        request: 0.1
      memory:
        request: 256M

controller:
  loglevel: DEBUG

traefik:
  loglevel: INFO
  dashboard: true
