apiVersion: skaffold/v2alpha3
kind: Config

build:
  local:
    push: false
    useBuildkit: true
  artifacts:
  - image: daskgateway/dask-gateway-server
    context: ./dask-gateway-server
    docker:
      dockerfile: Dockerfile
  - image: daskgateway/dask-gateway
    context: ./dask-gateway
    docker:
      dockerfile: Dockerfile

deploy:
  helm:
    releases:
    - name: dask-gateway
      chartPath: resources/helm/dask-gateway/
      namespace: default
      imageStrategy:
        helm: {}
      values:
        gateway.image: daskgateway/dask-gateway-server
        gateway.backend.image: daskgateway/dask-gateway
      valuesFiles:
        - resources/helm/testing/local-resources.yaml
    flags:
      upgrade:
      - --install
