# "skaffold" is a command line tool we can use to rebuild images for a Helm
# chart and even do some "live reload" of parts of an installation of a Helm
# chart.
#
# skaffolds purpose in this project is to be of assistance for local
# development, while we use the tool "chartpress" for testing and publishing of
# the Helm chart in our GitHub Workflows.
#
# Skaffold configuration reference: https://skaffold.dev/docs/references/yaml/
#
# FIXME:
# - Add notes on how to use skaffold
# - Update the skaffold/v2alpha3 configuration to a modern one
#
apiVersion: skaffold/v2alpha3
kind: Config

build:
  local:
    push: false
    useBuildkit: true
  artifacts:
  - image: ghcr.io/dask/dask-gateway-server
    context: ./dask-gateway-server
    docker:
      dockerfile: Dockerfile
  - image: ghcr.io/dask/dask-gateway
    context: ./dask-gateway
    docker:
      dockerfile: Dockerfile

deploy:
  helm:
    releases:
    - name: dask-gateway
      chartPath: resources/helm/dask-gateway/
      namespace: default
      imageStrategy:
        helm: {}
      values:
        gateway.image: ghcr.io/dask/dask-gateway-server
        gateway.backend.image: ghcr.io/dask/dask-gateway
        controller.image: ghcr.io/dask/dask-gateway-server
      valuesFiles:
        - resources/helm/testing/skaffold.yaml
    flags:
      upgrade:
      - --install

profiles:
  - name: local-controller
    patches:
      - op: add
        path: /deploy/helm/releases/0/setValues
        value:
          controller.enabled: false
