apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dask-gateway.fullname" . | printf "gateway-%s" | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "dask-gateway.labels" . | nindent 4 }}
  {{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "dask-gateway.labels" . | nindent 6 }}
      app.kubernetes.io/component: gateway
  template:
    metadata:
      labels:
        {{- include "dask-gateway.labels" . | nindent 8 }}
        app.kubernetes.io/component: gateway
    spec:
      {{- if .Values.rbac.enabled }}
      serviceAccountName: {{ include "dask-gateway.fullname" . }}
      {{- end }}
      volumes:
        - name: configmap
          configMap:
            name: {{ include "dask-gateway.fullname" . }}
      containers:
        - name: gateway
          image: {{ .Values.gateway.image.name }}:{{ .Values.gateway.image.tag }}
          imagePullPolicy: {{ .Values.gateway.image.pullPolicy }}
          command:
            - dask-gateway-server
            - --config
            - /etc/dask-gateway/dask_gateway_config.py
          resources:
            {{- .Values.gateway.resources | toYaml | trimSuffix "\n" | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/dask-gateway/
              name: configmap
          env:
            - name: DASK_GATEWAY_PROXY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "dask-gateway.fullname" . }}
                  key: proxy-token
            {{- if .Values.gateway.cookieSecret }}
            - name: DASK_GATEWAY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "dask-gateway.fullname" . }}
                  key: cookie-secret
            {{- end }}
            {{- if (eq .Values.gateway.auth.type "jupyterhub") }}
            - name: JUPYTERHUB_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "dask-gateway.fullname" . }}
                  key: jupyterhub-api-token
            {{- end }}
            - name: SCHEDULER_PROXY_PUBLIC_SERVICE_NAME
              value: {{ include "dask-gateway.fullname" . | printf "scheduler-public-%s" | trunc 63 | trimSuffix "-" }}
            - name: SCHEDULER_PROXY_API_SERVICE_NAME
              value: {{ include "dask-gateway.fullname" . | printf "scheduler-api-%s" | trunc 63 | trimSuffix "-" }}
            - name: WEB_PROXY_PUBLIC_SERVICE_NAME
              value: {{ include "dask-gateway.fullname" . | printf "web-public-%s" | trunc 63 | trimSuffix "-" }}
            - name: WEB_PROXY_API_SERVICE_NAME
              value: {{ include "dask-gateway.fullname" . | printf "web-api-%s" | trunc 63 | trimSuffix "-" }}
          ports:
            - containerPort: 8001
              name: api
