kind: ConfigMap
apiVersion: v1
metadata:
  name: gateway-config
  labels:
    {{- include "dask-gateway.labels" . | nindent 4 }}
data:
  values.yaml: |
    {{/* Remove secrets before forwarding configuration */}}
    {{- $values := pick .Values "gateway" "schedulerProxy" "webProxy" }}
    {{- $_ := set $values "gateway" (omit $values.gateway "cookieSecret" "proxyToken") }}
    {{- $values | toYaml | nindent 4 }}
