apiVersion: v1
kind: Service
metadata:
  name: {{ include "dask-gateway.fullname" . | printf "gateway-api-%s" | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "dask-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway-api
spec:
  selector:
    {{- include "dask-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
