{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "dask-gateway.fullname" . }}
  labels:
    {{- include "dask-gateway.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host | quote }}
      http:
        paths:
          - path: {{ $.Values.ingress.path }}
            backend:
              serviceName: {{ include "dask-gateway.fullname" $ }}
              servicePort: http
    {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | trimSuffix "\n" | nindent 4 }}
  {{- end }}
{{- end }}
