apiVersion: v1
kind: Service
metadata:
  name: {{ include "dask-gateway.fullname" . | printf "scheduler-api-%s" | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "dask-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: scheduler-proxy-api
  {{- with .Values.schedulerProxy.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "dask-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: scheduler-proxy
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dask-gateway.fullname" . | printf "scheduler-public-%s" | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "dask-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: scheduler-proxy-public
  {{- with .Values.schedulerProxy.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "dask-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: scheduler-proxy
  ports:
    - protocol: TCP
      port: 8786
      targetPort: 8786
  type: {{ .Values.schedulerProxy.service.type }}
