kind: Secret
apiVersion: v1
metadata:
  name: {{ include "dask-gateway.fullname" . }}
  labels:
    {{- include "dask-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  proxy-token: {{ (required "gateway.proxyToken must be a 32 byte random string" .Values.gateway.proxyToken) | b64enc | quote }}

  {{- if .Values.gateway.cookieSecret }}
  cookie-secret: {{ .Values.gateway.cookieSecret | b64enc | quote }}
  {{- end }}
