apiVersion: v1
kind: Service
metadata:
  name: web-proxy-api
  labels:
    {{- include "dask-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: web-proxy
spec:
  selector:
    {{- include "dask-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: web-proxy
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: web-proxy-public
  labels:
    {{- include "dask-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: web-proxy
spec:
  selector:
    {{- include "dask-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: web-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
