apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dask-gateway.fullname" . | printf "web-proxy-%s" | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "dask-gateway.labels" . | nindent 4 }}
  {{- with .Values.webProxy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "dask-gateway.labels" . | nindent 6 }}
      app.kubernetes.io/component: web-proxy
  template:
    metadata:
      labels:
        {{- include "dask-gateway.labels" . | nindent 8 }}
        app.kubernetes.io/component: web-proxy
    spec:
      volumes:
        - name: configmap
          configMap:
            name: {{ include "dask-gateway.fullname" . }}
      containers:
        - name: web-proxy
          image: {{ .Values.webProxy.image.name }}:{{ .Values.webProxy.image.tag }}
          imagePullPolicy: {{ .Values.webProxy.image.pullPolicy }}
          command:
            - dask-gateway-server
            - web-proxy
            - --config
            - /etc/dask-gateway/dask_gateway_config.py
          resources:
            {{- .Values.webProxy.resources | toYaml | trimSuffix "\n" | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/dask-gateway/
              name: configmap
          env:
            - name: DASK_GATEWAY_PROXY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "dask-gateway.fullname" . }}
                  key: proxy-token
            - name: DASK_GATEWAY_PROXY_CONTAINER
              value: "true"
          ports:
            - containerPort: 8001
              name: api
            - containerPort: 8000
              name: public
