version: 2.1

jobs:
  test_core:
    docker:
      - image: daskgateway/circleci-common:latest
    steps:
      - checkout
      - run:
          name: Install
          shell: /bin/bash -elo pipefail
          command: |
            set -xe
            conda install \
              configurable-http-proxy \
              aiohttp \
              black \
              colorlog \
              cryptography \
              dask-core \
              distributed \
              flake8 \
              ipywidgets \
              jupyterhub \
              notebook \
              pytest \
              pytest-asyncio=0.12.0 \
              sqlalchemy \
              tornado \
              traitlets

            pip install -U trustme

            pushd dask-gateway
            python setup.py develop
            popd

            pushd dask-gateway-server
            python setup.py develop
            popd

            pip list
      - run:
          name: Run core tests
          shell: /bin/bash -elo pipefail
          command: py.test tests/ -v
      - run:
          name: Run flake8
          shell: /bin/bash -elo pipefail
          command: flake8
      - run:
          name: Run black
          shell: /bin/bash -elo pipefail
          command: black . --check
      - run:
          name: Run Go tests
          shell: /bin/bash -elo pipefail
          command: |
            pushd dask-gateway-server/dask-gateway-proxy
            go test
            popd

workflows:
  version: 2

  test_core:
    jobs:
      - test_core
