version: 2.1

jobs:
  test_core:
    docker:
      - image: daskgateway/circleci-common:latest
    steps:
      - checkout
      - run:
          name: Install
          shell: /bin/bash -elo pipefail
          command: |
            conda install \
              configurable-http-proxy \
              aiohttp \
              colorlog \
              cryptography \
              dask-core \
              distributed \
              ipywidgets \
              jupyterhub \
              notebook \
              sqlalchemy \
              tornado \
              traitlets

            pip install -U trustme black flake8 pytest pytest-asyncio==0.12.0

            pushd dask-gateway
            python setup.py develop
            popd

            pushd dask-gateway-server
            python setup.py develop
            popd

            pip list
      - run:
          name: Run core tests
          shell: /bin/bash -elo pipefail
          command: py.test tests/ -v
      - run:
          name: Run flake8
          shell: /bin/bash -elo pipefail
          command: flake8
      - run:
          name: Run black
          shell: /bin/bash -elo pipefail
          command: black . --check
      - run:
          name: Run Go tests
          shell: /bin/bash -elo pipefail
          command: |
            pushd dask-gateway-server/dask-gateway-proxy
            go get github.com/stretchr/testify/assert
            CGO_ENABLED=0 go test
            popd

  test_kube:
    machine: true
    steps:
      - checkout
      - run:
          name: Trial
          command: echo "Hello"

workflows:
  version: 2

  tests:
    jobs:
      - test_core
      - test_kube
