apiVersion: gateway.dask.org/v1alpha1
kind: DaskCluster
metadata:
  name: dask
  namespace: default
spec:
  scheduler:
    template:
      metadata:
        name: scheduler
        namespace: default
      spec:
        containers:
        - name: nginx
          image: nginx:1.7.9
  worker:
    template:
      metadata:
        name: worker
        namespace: default
      spec:
        containers:
        - name: nginx
          image: nginx:1.7.9
    replicas: 5
  active: false
