# These are the requirements we know we want to install in the Dockerfile, and
# then we freeze them ahead of time to provide a clear description of the
# dependencies we have installed.
#

# Install dask-gateway-server[kubernetes], which is the only thing needed for
# our CI test suite.
#
.[kubernetes]
