# These are the requirements we know we want to install in the Dockerfile, and
# then we freeze them ahead of time to provide a clear description of the
# dependencies we have installed.
#

# Install dask-gateway, which is the only thing needed for our CI test suite.
.

# We also install the bare minimum to provide end users with a primitive
# end-to-end demonstrative test doing work in the worker pods and accessing the
# scheduler dashboard without changing the image.
#
# - bokeh is required by the scheduler pod to present dashbaords.
# - numpy is required for running a basic computation test:
#   https://gateway.dask.org/usage.html#run-computations-on-the-cluster
#
bokeh
numpy
