{{- if .Values.rbac.enabled -}}
{{- if .Values.traefik.installTraefik -}}
{{- if not .Values.rbac.traefik.serviceAccountName -}}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "dask-gateway.traefikName" . }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "dask-gateway.traefikName" . }}
# The rules below are from Traefik's Helm chart, most recently 21 Jan 2025 from
# commit 4e15c7c for use with Traefik v3.2.0.
#
# To update them again, you can do:
#
#   git clone https://github.com/traefik/traefik-helm-chart
#   cd traefik-helm-chart
#   helm template traefik --show-only templates/rbac/clusterrole.yaml --set providers.kubernetesIngress.enabled=false
#
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - secrets
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - list
      - watch
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingressclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - traefik.io
    resources:
      - ingressroutes
      - ingressroutetcps
      - ingressrouteudps
      - middlewares
      - middlewaretcps
      - serverstransports
      - serverstransporttcps
      - tlsoptions
      - tlsstores
      - traefikservices
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "dask-gateway.traefikName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "dask-gateway.traefikName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "dask-gateway.traefikName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
{{- end }}