{{- if .Values.rbac.enabled -}}
{{- if not .Values.rbac.traefik.serviceAccountName }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "dask-gateway.traefikName" . }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "dask-gateway.traefikName" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses/status
    verbs:
      - update
  - apiGroups:
      - traefik.containo.us
    resources:
      - ingressroutes
      - ingressroutetcps
      - middlewares
      - tlsoptions
      - traefikservices
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "dask-gateway.traefikName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "dask-gateway.traefikName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "dask-gateway.traefikName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
