name: Docs

on:
  push:
    branches: [ "main" ]

env:
  commit_msg: ${{ github.event.head_commit.message }}

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14'

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '6'
      - name: Install requirements
        run: |
          go get github.com/stretchr/testify/assert
          source continuous_integration/install.sh

      - name: Install
        run: |
          source continuous_integration/install.sh
          pip install kubernetes_asyncio skein sphinx==3.3.1 doctr dask-sphinx-theme sphinx-rtd-theme==0.4.3
      - name: Build docs
        run: |
          pushd docs
          make html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs/build/html/
